# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 10:32
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
